### ISSUE TITLE
bitwise operators for floats

### ISSUE THREAD

**Issue by skgbanga** [ospray/tsimd#14]
Hello,

I watched your cppcon talk https://youtu.be/8khWb-Bhhvs, and thought I would convert our code written with intrinsics to tsimd.

One of the missing things I noticed is that there is no bitwise AND for float i.e. equivalent of
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=5006,2,297&text=_mm512_and_ps

Are there any plans to support that?

**Comment by jeffamstutz** [comment]
I'm glad you found the talk from last year! I hope it was helpful. :)

In general, I made `pack<>` implicitly convert to their underlying intrinsic type, so if you find anything missing you can always fallback to using the raw intrinsic.

However, this is easy enough to add, which I can do right now.

I will note that `tsimd` hasn't really been active as OSPRay is relying on [ISPC](https://ispc.github.io/) for SIMD parallelism. We found that large, branchy code bases still greatly benefit from direct langague support, so we never ported off of ISPC/C++ to pure C++. Regardless, `tsimd` still has plenty to offer.

A couple of questions:

- what minimum C++ standard do you require? If you can use C++17, the recently published [Enoki](https://github.com/mitsuba-renderer/enoki) library looks like a nice superset of what tsimd can do.
- does your code have lots of per-lane branching (masks)? If yes, then ISPC may be a good option to consider.

**Comment by jeffamstutz** [comment]
I just added operators &, |, and ^ for floats and doubles in 0dd4365.

I don't have any CI setup and I'm only on my laptop right now, so I hope I typed them all in correctly the first time. ;)

**Comment by skgbanga** [comment]
@jeffamstutz The talk was great. thanks!

Also thanks for quickly adding these, and for other pointers. We do use c++17, so I will take a look at the Enoki. ispc also looks super interesting. 

Thanks once again!
